source "https://rubygems.org"

gem "rails", "3.2.8"

group :test do
  gem "rspec-rails", :require => false
  gem "turn", :require => false
end

group :development, :test do
  gem "sqlite3-ruby", :require => "sqlite3"
end

group :production do
  gem "nginxtra", :require => false
  gem "passenger", :require => false
  gem "mysql2"
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem "sass-rails"
  gem "coffee-rails"
  gem "therubyracer"
  gem "uglifier"
end

gem "jquery-rails"

# To use Jbuilder templates for JSON
# gem "jbuilder"
